security:
    encoders:
        Drm\BlogBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 10

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: "DrmBlogBundle:User", property: username }

    firewalls:
        admin_area:
            pattern:    ^/blog
            http_basic: ~

    access_control:
        - { path: ^/blog, roles: ROLE_ADMIN }