security:
    firewalls:
         secure_area:
            pattern:    ^/
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                path:   /logout
                target: /   
            anonymous: ~
         insecure:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
    
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
         
    access_control:
        - { path: ^/blog/, roles: ROLE_ADMIN }
        - { path: ^/user/, roles: ROLE_ADMIN }

    providers:
        administrators:
            entity: { class: "DrmBlogBundle:User", property: username }

    encoders:
        Drm\BlogBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 10
