DrmBlogBundle_blog:
    resource: "@DrmBlogBundle/Resources/config/routing/blog.yml"
    prefix:   /blog

DrmBlogBundle_user:
    resource: "@DrmBlogBundle/Resources/config/routing/user.yml"
    prefix:   /user

DrmBlogBundle_homepage:
    pattern: /
    defaults: {_controller: "DrmBlogBundle:Page:index" }
    requirements:
        _method:  GET

DrmBlogBundle_blogs:
    pattern: /blogs/{tag}/{page}
    defaults: {_controller: "DrmBlogBundle:Page:blogs", tag: "all", page: 1 }
    requirements:
        _method:  GET

        
DrmBlogBundle_about:
    pattern:  /whoami
    defaults: { _controller: "DrmBlogBundle:Page:about" }
    requirements:
        _method:  GET

DrmBlogBundle_disclaimer:
    pattern:  /disclaimer
    defaults: { _controller: "DrmBlogBundle:Page:disclaimer" }
    requirements:
        _method:  GET
        
DrmBlogBundle_contact:
    pattern:  /contact
    defaults: { _controller: "DrmBlogBundle:Page:contact" }
    requirements:
        _method:  GET|POST
       
DrmBlogBundle_blog_show:
    pattern:  /{id}/{slug}
    defaults: { _controller: "DrmBlogBundle:Blog:show" }
    requirements:
        _method:  GET
        id: \d+
        
DrmBlogBundle_comment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: "DrmBlogBundle:Comment:create" }
    requirements:
        _method:  POST
        blog_id: \d+
        