DrmBlogBundle_homepage:
    pattern:  /
    defaults: { _controller: "DrmBlogBundle:Page:index" }
    requirements:
        _method:  GET
        
DrmBlogBundle_about:
    pattern:  /about
    defaults: { _controller: "DrmBlogBundle:Page:about" }
    requirements:
        _method:  GET
        
DrmBlogBundle_contact:
    pattern:  /contact
    defaults: { _controller: "DrmBlogBundle:Page:contact" }
    requirements:
        _method:  GET|POST
       
DrmBlogBundle_blog_show:
    pattern:  /{id}/{slug}
    defaults: { _controller: "DrmBlogBundle:Blog:show" }
    requirements:
        _method:  GET
        id: \d+
        
DrmBlogBundle_comment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: "DrmBlogBundle:Comment:create" }
    requirements:
        _method:  POST
        blog_id: \d+
        
DrmBlogBundle_blog_add:
    pattern:  /blog/add/
    defaults: { _controller: "DrmBlogBundle:Blog:add" }
    requirement:
      _method:  GET|POST