parameters:
#    drm_blog.example.class: Drm\BlogBundle\Example

services:
#    drm_blog.example:
#        class: %drm_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    drm_blog.twig.extension:
        class: Drm\BlogBundle\Twig\Extensions\DrmBlogExtension
        tags:
            - { name: twig.extension }
